language: node_js
sudo: true
node_js: stable
env:
  global:
  - CF_APP=hackathon-700DO
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=jotase
  - CF_SPACE=dev
before_deploy: npm install -g cf-blue-green
install: npm install mercadolibre
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: https://github.com/JotaSe/hackathon-700DO
  skip_cleanup: true
notifications:
  email: false
